FROM node:22-bookworm-slim AS builder

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build -w bot

FROM node:22-slim

WORKDIR /app

COPY --from=builder --chown=node ./app/bot/dist ./dist
COPY --from=builder --chown=node ./app/bot/package.json .
COPY --from=builder --chown=node ./app/package-lock.json .

RUN npm install --production

USER node

CMD ["node", "dist/index.js"]
