name: Deploy bot docker image

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Set up Kubernetes context
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "${KUBECONFIG}" > ~/.kube/config
      - name: Helm upgrade
        env:
            DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
            DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
            OSU_CLIENT_ID: ${{ secrets.OSU_CLIENT_ID }}
            OSU_REDIRECT_URI: ${{ vars.OSU_REDIRECT_URI }}
            OSU_CLIENT_SECRET: ${{ secrets.OSU_CLIENT_SECRET }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            OPTIONAL_DATABASE_AUTH_TOKEN: ${{ secrets.OPTIONAL_DATABASE_AUTH_TOKEN }}
            IMAGE: ${{ vars.IMAGE }}
          # Please for the love of god, just wrap every env in quotes like this: "'${VARIABLE}'"
          # Just makes sure all the values are strings and nothing breaks
        run: |
          helm upgrade --install osu-crew-bot ./helm/osu-crew-bot --create-namespace --namespace production \
          --set osu_crew_bot.DISCORD_TOKEN="'${DISCORD_TOKEN}'" \
          --set osu_crew_bot.DISCORD_CLIENT_ID="'${DISCORD_CLIENT_ID}'" \
          --set osu_crew_bot.NODE_ENV=production \
          --set osu_crew_bot.OSU_CLIENT_ID="'${OSU_CLIENT_ID}'" \
          --set osu_crew_bot.OSU_CLIENT_SECRET="'${OSU_CLIENT_SECRET}'" \
          --set osu_crew_bot.OSU_REDIRECT_URI="'${OSU_REDIRECT_URI}'" \
          --set osu_crew_bot.JWT_SECRET="'${JWT_SECRET}'" \
          --set osu_crew_bot.DATABASE_URL="'${DATABASE_URL}'" \
          --set osu_crew_bot.OPTIONAL_DATABASE_AUTH_TOKEN="'${OPTIONAL_DATABASE_AUTH_TOKEN}'" \
          --set osu_crew_bot.image="'${IMAGE}'" \
          --set osu_crew_bot.mem_limit=512Mi \
          --set osu_crew_bot.cpu_limit=250m
