name: Build bot docker image

on:
  workflow_dispatch:
  push: 
    branches:
      - container-build

concurrency:
  group: "docker"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.bot
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - name: Logout of GHCR
        run: docker logout ghcr.io
